In [59]:
import numpy as np

### Funcion para determinar si la matriz es diagonalmente dominante
def is_diagonally_dominant(A):
    n = len(A)
    #print(n)

    for i in range(0, n):
        row_sum = 0
        for j in range(0, n):
            row_sum += abs(A[i][j])

        row_sum -= abs(A[i][i])

        if abs(A[i][i]) < row_sum:
            return False
    return True
## Funcion para determinar si la matriz es definida positiva
def is_pos_def(x):
    return np.all(np.linalg.eigvals(x) > 0)

## Funcion para enconrar la matriz TJ
def calculate_TJ(matrix_A):
    n = len(matrix_A)
    TJ = np.zeros((n, n))

    for i in range(n):
        for j in range(n):
            if i != j:
                TJ[i][j] = -matrix_A[i][j] / matrix_A[i][i]

    return TJ

## Funcion para encontar el radio espectral
def calculate_spectral_radius(matrix_TJ):
    eigenvalues, _ = np.linalg.eig(matrix_TJ)
    spectral_radius = np.max(np.abs(eigenvalues))
    return spectral_radius

## Matriz para conseguir omega
def calculate_omega(spectral_radius):
    omega = 2.0 / (1.0 + np.sqrt(1.0 - spectral_radius**2))
    return omega

## Funcion algoritmo SOR
def gauss_seidel_sor(A, b, omega, tol=1e-6, max_iter=1000):
    n = len(b)
    x = np.zeros(n)
    normVal = float('inf')
    itr = 0

    while normVal > tol:
      x_old = np.copy(x)

      for i in range(n):
          sigma = 0

          for j in range(i):
              sigma += A[i, j] * x[j]


          for j in range(i + 1, n):
              sigma += A[i, j] * x_old[j]
          print(f"sigma={sigma}")
          x[i] = ((1 - omega) * x_old[i]) + ((omega / A[i, i]) * (b[i] - sigma))

      print(f"x={x}")
      itr += 1
      normVal = np.linalg.norm(x-x_old)
      print(f"nomrval = {normVal}")
      if itr == max_iter:
          print("No converge en el número máximo de iteraciones.")

    return x, itr


## Matriz de prueba
A = np.array([[10, -1,0],
              [-1, 10, -2],
              [0, -2, 10]])

## Vector de resultados
b = np.array([9, 7, 6])

# Tolerance for method
tol = 1e-6
itr = 0

## resultados de diagonal y positiva
print("Es diagonal mente dominante:", is_diagonally_dominant(A))
print("Es definida positiva: ", is_pos_def(A))

# Encontara TJ
TJ = calculate_TJ(A)
print("Matriz TJ:")
print(TJ)

## calcular el radio espectral
spectral_radius = calculate_spectral_radius(TJ)
print("Radio espectral:", spectral_radius)

## Calcular omega
omega = calculate_omega(spectral_radius)
print("Parámetro de relajación omega:", omega)

solution, iterations = gauss_seidel_sor(A, b, omega)

print("Solution of the system is:")
print(solution)
print(f"Converged in {iterations} iterations")


Es diagonal mente dominante: True
Es definida positiva:  True
Matriz TJ:
[[0.  0.1 0. ]
 [0.1 0.  0.2]
 [0.  0.2 0. ]]
Radio espectral: 0.22360679774997907
Parámetro de relajación omega: 1.0128226207641444
sigma=0.0
sigma=-0.91154035868773
sigma=-1.602597408073481
x=[0.91154036 0.8012987  0.77000826]
nomrval = 1.4373232635425424
sigma=-0.8012987040367405
sigma=-2.5210258939927406
sigma=-1.9080725808620747
x=[0.98100937 0.95403629 0.79107396]
nomrval = 0.16911084209488678
sigma=-0.9540362904310373
sigma=-2.577736112618679
sigma=-1.9156430670191111
x=[0.9955882  0.95782153 0.79157059]
nomrval = 0.0150704048108336
sigma=-0.9578215335095556
sigma=-2.578925828899294
sigma=-1.9157869878583789
x=[0.99578464 0.95789349 0.7915788 ]
nomrval = 0.00020936573577375408
sigma=-0.9578934939291894
sigma=-2.5789470151890135
sigma=-1.9157894340067325
x=[0.99578941 0.95789472 0.79157895]
nomrval = 4.925836571285623e-06
sigma=-0.9578947170033663
sigma=-2.5789473629038513
sigma=-1.9157894730753902
x=[0.9957

In [23]:
import numpy as np

def calculate_TJ(matrix_A):
    n = len(matrix_A)
    TJ = np.zeros((n, n))

    for i in range(n):
        for j in range(n):
            if i != j:
                TJ[i][j] = -matrix_A[i][j] / matrix_A[i][i]

    return TJ

# Ejemplo de matriz A
A = np.array([[3, 1,-1],
              [2, 4, -1],
              [-1, 2, 5]])

TJ = calculate_TJ(A)
print("Matriz TJ:")
print(TJ)




Matriz TJ:
[[ 0.         -0.33333333  0.33333333]
 [-0.5         0.          0.25      ]
 [ 0.2        -0.4         0.        ]]


In [24]:
def calculate_spectral_radius(matrix_TJ):
    eigenvalues, _ = np.linalg.eig(matrix_TJ)
    spectral_radius = np.max(np.abs(eigenvalues))
    return spectral_radius
spectral_radius = calculate_spectral_radius(TJ)
print("Radio espectral:", spectral_radius)


Radio espectral: 0.4860151996388082


In [25]:
def calculate_omega(spectral_radius):
    omega = 2.0 / (1.0 + np.sqrt(1.0 - spectral_radius**2))
    return omega


omega = calculate_omega(spectral_radius)
print("Parámetro de relajación omega:", omega)


Parámetro de relajación omega: 1.0672641316274192


In [28]:
def gauss_seidel_sor(A, b, omega, tol=1e-6, max_iter=1000):
    n = len(b)
    x = np.zeros_like(b)
    normVal = np.inf
    itr = 0

    while normVal > tol and itr < max_iter:
        x_old = np.copy(x)

        for i in range(n):
            sigma = np.dot(A[i, :i], x[:i]) + np.dot(A[i, i + 1:], x_old[i + 1:])
            x[i] = (1 - omega) * x_old[i] + (omega / A[i, i]) * (b[i] - sigma)

        itr += 1
        normVal = np.linalg.norm(x_old - x)

    if itr == max_iter:
        print("No converge en el número máximo de iteraciones.")

    return x, itr

solution, iterations = gauss_seidel_sor(A, b, omega)

print("Solution of the system is:")
print(solution)
print(f"Converged in {iterations} iterations")

Solution of the system is:
[10 -4  3]
Converged in 3 iterations


In [57]:
# Gauss Seidel Method
while normVal > tol:
    x_old = np.copy(x)

    for i in range(n):
        sigma = 0

        for j in range(i):
            sigma += A[i, j] * x[j]

        for j in range(i + 1, n):
            sigma += A[i, j] * x_old[j]

        x[i] = (1 / A[i, i]) * (b[i] - sigma)

    itr += 1
    normVal = np.linalg.norm(x_old - x)